dt_save_to_disk: "10days"
dt: "100secs" 
t_end: "1000days"
h_elem: 16
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
zd_rayleigh: 35000.0
z_elem: 63
vert_diff: "true" 
kappa_4: 3e16
alpha_rayleigh_w: 1.0
surface_setup: "DefaultExchangeCoefficients" 
moist: "equil" 
rad: "gray" 
precip_model: "0M" 
topography: "Earth"
topo_smoothing: true
job_id: "longrun_aquaplanet_rhoe_equil_gray_55km_nz63_0M" 
output_dir: "/central/scratch/asridhar/Milestone_1-5-2a/1992"
